name: CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up vcpkg
      run: |
        # Workaround for failing grub-efi installation during upgrade
        echo 'APT::Get::Always-Include-Phased-Updates "false";' | sudo tee /etc/apt/apt.conf.d/99-phased-updates
        sudo apt update
        sudo apt upgrade -y
        sudo apt install -y cmake
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Download Unit Test Designs
      run: |
        python -m pip install -r test/py/requirements.txt
        python test/py/testing.py --download_repos true --database_file_path repos.yaml --third_party_path test/designs

    - name: Create Unit Tests
      run: |
        python test/py/testing.py --generate_unit_tests true --database_file_path repos.yaml --unit_test_path test/src/generated_tests --third_party_path test/designs

    - name: Build Library, CLI Application and Tests
      run: |
        export VCPKG_ROOT=$(realpath ./vcpkg)
        cmake --preset release -DENABLE_UNIT_TESTING=ON
        cmake --build --preset release -j $(nproc)

    - name: Run Tests
      run: |
        python3 run_tests.py